# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0002_auto_20160829_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='pswd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reuse.Pswd_table'),
        ),
    ]
