# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0004_ctf_info_config_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
