# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0005_auto_20160831_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
